// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSIEiOkGJe76DNrNbTIU3eAs9rgbWP-fY',
    appId: '1:715456222329:web:43d9f63f4b9acf0d5af0a8',
    messagingSenderId: '715456222329',
    projectId: 'qapture-pit',
    authDomain: 'qapture-pit.firebaseapp.com',
    storageBucket: 'qapture-pit.appspot.com',
    measurementId: 'G-WFGH8WMC5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUoG9VGyCjcOOVbcv--niTVvg6cUxqmFA',
    appId: '1:715456222329:android:ddfa07aee616e2d05af0a8',
    messagingSenderId: '715456222329',
    projectId: 'qapture-pit',
    storageBucket: 'qapture-pit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzcJK4vEIemNqnC8Gd22SsE8K1r5_CY8Y',
    appId: '1:715456222329:ios:5d526a79d455be105af0a8',
    messagingSenderId: '715456222329',
    projectId: 'qapture-pit',
    storageBucket: 'qapture-pit.appspot.com',
    iosBundleId: 'com.example.login2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzcJK4vEIemNqnC8Gd22SsE8K1r5_CY8Y',
    appId: '1:715456222329:ios:4fbeb04dfa9b8fee5af0a8',
    messagingSenderId: '715456222329',
    projectId: 'qapture-pit',
    storageBucket: 'qapture-pit.appspot.com',
    iosBundleId: 'com.example.login2.RunnerTests',
  );
}
